### ISSUE TITLE
Update docs to allow Spaceflights tutorial run with 'kedro<0.18' and kedro-kubeflow==0.6.2 

### ISSUE THREAD

**Issue by michalbrys** [getindata/kedro-kubeflow#119]
`kedro new --starter=spaceflights` doesn't work out of the box on Kubeflow Pipelines and package versions:
```
kedro<0.18
kedro-kubeflow==0.6.2 
```

## Proposed updates:

1) Add kedro-kubeflow in requirements files to solve the problem during onExit node execution:
```Error: no such command 'kubeflow'```

Add: in `requirements.txt` / `requirements.in`
```
kedro-kubeflow==0.6.2 
```

2) Add pipeline outputs to allow save data processing nodes outputs as `pickle.PickleDataSet`

`src/spaceflights/data_processing/pipeline.py`

```
        inputs=["companies", "shuttles", "reviews"],
        ## Add this line
        outputs=["model_input_table","preprocessed_shuttles", "preprocessed_companies"]
    )
```

3) Solve the unsupported `.` character in the node name.

In the latest Spaceflights starter, we have 2 sub-pipelines for the data science part: active_modelling_pipeline and candidate_modelling_pipeline in `src/spaceflights/data_science/pipeline.py`.

When we add pipeline outputs like in 2) above, output names will look like this: "active_modelling_pipeline.X_train" and we can't compile it to Kubeflow Pipeline because of unallowed `.` in the node name added by the namespace.

We can temporarily resolve this issue by removing `candidate_modelling_pipeline` and keeping only one pipeline like this:

`src/spaceflights/data_science/pipeline.py`
```
 ds_pipeline = pipeline(
        pipe=pipeline_instance,
        inputs="model_input_table"
    )
    return pipeline(
        pipe=ds_pipeline, 
        inputs="model_input_table",
        namespace="data_science",
        ## Add this
        outputs=["regressor", "X_train", "X_test", "y_train", "y_test"],
```

but this is rather a workaround than the root cause solution.

**Comment by Lasica** [comment]
Yes I've encountered all these issues when making local setup recently and I plan to update the docs to reflect that.
Maybe we could prepare our own spaceflight-like object for kedro to pull as a fully working example alternative?

**Comment by Lasica** [comment]
I've updated the docs to provide working example for now. The issue with namespaces has been moved to separate issue.
