### ISSUE TITLE
Add 'kedro-kubeflow' to requirements when initializing with `kedro kubeflow init`

### ISSUE THREAD

**Issue by Lasica** [getindata/kedro-kubeflow#161]
For some reason (which I do not fully understand) kedro-kubeflow is used during kedo run inside docker images when executing docker image. It causes issue if you forget to add that dependency and it has to be added manually when generating a starter pack.

Maybe we could automate that and eliminate this step during: `kedro kubeflow init`?

**Comment by marrrcin** [comment]
Closing (added to docs).
