### ISSUE TITLE
Add support to kedro namespaces for parameters

### ISSUE THREAD

**Issue by DmitriyLamzin** [getindata/kedro-kubeflow#219]
namespaced kedro parameters in general look like:

`outer_namespace.inner_namespace.param_name`

kubeflow doesn't accept dots in parameter names so during compiling the Error is raised:

`ValueError: 'outer_namespace.inner_namespace.param_name' is not a valid parameter name`

One of the fixes I see is to merge such parameters in structure so it to became looks like this:

```json
{
  "outer_namespace": {
      "inner_namespace": {
        "param_name": "value",
        ...
      },
      "another_inner_namespace": {
        "param_name": "value"
        ...
      } 
  }
}
```

**Comment by marrrcin** [comment]
We will be happy to accept this fix as a PR if you're willing to contribute 🙂
