### ISSUE TITLE
State of the project and plans for supporting kedro 0.19?

### ISSUE THREAD

**Issue by swertz** [getindata/kedro-kubeflow#265]
Hello,

We are interested in using kedro-kubeflow for a project to be put into production, so we would like to understand better how well it is going to be supported in the future. The last merged PRs are several months old, so we are hesitating to depend on this package for that project...

Im particular, what are your plans for supporting Kedro 0.19?

Let us know if there is anything we could help with!

**Comment by Lasica** [comment]
We're currently occupied with other projects, but yes - we plan to maintain the plugin and update it to 0.19. I'll probably have some time for it at the end of the month. If you want to commit PR to update it yourself, feel free and I'll find a time to review & merge it.
