### ISSUE TITLE
-e flag not working

### ISSUE THREAD

**Issue by em-pe** [getindata/kedro-kubeflow#58]
```
$ kedro kubeflow run-once -e central
Usage: kedro kubeflow run-once [OPTIONS]
Try 'kedro kubeflow run-once -h' for help.
Error: no such option: -e
```

**Comment by michalzelechowski-getindata** [comment]
> ```
> $ kedro kubeflow run-once -e central
> Usage: kedro kubeflow run-once [OPTIONS]
> Try 'kedro kubeflow run-once -h' for help.
> Error: no such option: -e
> ```

@em-pe Did you try kedro kubeflow -e central run-once?
