### ISSUE TITLE
Documentation for Vertex AI updates

### ISSUE THREAD

**Issue by mwiewior** [getindata/kedro-kubeflow#99]
I didn't find any info in the documentation that optional extension `kedro-kubeflow[vertex]` and `google-cloud-aiplatform` should be installed.

**Comment by szczeles** [comment]
Good point! It works without need to install `google-cloud-aiplatform`, as `AIPlatformClient` is shipped as part of `kfp`:

```
from kfp.v2.google.client import AIPlatformClient
```

**Comment by szczeles** [comment]
VertexAI support is now provided as https://github.com/getindata/kedro-vertexai/ plugin, closing the issue.
